### ISSUE TITLE
Trying to test under Windows

### ISSUE THREAD

**Issue by bdelaney** [jsturtevant/vscode-softwrap#1]
Installed softwrap, but see no key assignment.
Have a markdown file open but cannot see how to wordrap in source window.

**Comment by jsturtevant** [comment]
It does not work on windows currently. Should have an update to work on all platforms by end of the week.

**Comment by jsturtevant** [comment]
Tested it on windows.  See the project [ReadMe.Md](https://github.com/jsturtevant/vscode-softwrap/blob/master/README.md) for latest instructions to run it.
